Draft: Evol/list react table
Coreoz/create-plume-react-project pull request #11
Opened 2022-12-06 12:52 UTC by benjaminchardin2

Je vous fais la MR en draft pour pas partir trop loin sans retours

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-theme/action/ActionProps.ts
> +  variant?: 'contained' | 'outlined' | 'text'
manque une virgule à la fin de la ligne.

D'ailleurs je vois que tu utilise ici et plus bas des ';' à la fin des lignes des types alors que tu utilise des ',' pour la même chose quand tu défini les props dans ton composant. Est-ce que l'un des deux est mieux que l'autre ? En tout cas il faudrait uniformiser ça

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/components/theme/list/sort/SortMenu.tsx
> +  }
il manque une virgule ici

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/i18n/translations/Translations.ts
> +  }
virgule

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/i18n/translations/Translations.ts
> +  }
2 virgules qui manquent

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/i18n/translations/en.ts
> +      fullName_asc: 'Sort by ascendant alphabetical order',
je ne sais pas à quel point le wording est important ou pas mais est-ce que c'est vraiment utile de préciser 'ascendant' ici  ?

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/i18n/translations/fr.ts
> +      fullName_asc: 'Trier par ordre alphabétique ascendant',
pareil pour le 'acscendant'

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-theme/list/filter/FilterProps.ts
> +  possibleValues: string[]
virgule

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-users/components/UserTile.tsx
> +  creationDate: string
virgules

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-users/components/UserTile.tsx
> +            `}
faire une fonction pour ça ?

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-users/components/UserTile.tsx
> +          <span className="value value--little">{dayjs(user.creationDate).format('L LT')}</span>
est-ce qu'on peut mettre les formats de date dans le I18n ?

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-users/components/UsersListResults.tsx
> +  table: TableType<AdminUserDetails>
virgules

2022-12-07 17:26 UTC, prateau commented on templates/admin/src/lib/plume-admin-users/pages/Users.tsx
> +    const userLoader = useLoader();
const { monitor, isLoading } = useLoader();

2022-12-08 17:15 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/components/UserTile.tsx
> +          <span className="value value--little">{dayjs(user.creationDate).format('L LT')}</span>
on pourrait mais c'est relativement universel comme format et c'est déjà localizé donc pas besoin 
PI : https://momentjscom.readthedocs.io/en/latest/moment/07-customization/06-long-date-formats/

2022-12-08 17:15 UTC, benjaminchardin2 commented on templates/admin/assets/scss/components/_user-tile.scss
> +          padding: .5rem;
done

2022-12-08 17:16 UTC, benjaminchardin2 commented on templates/admin/src/components/theme/list/ListHeader.tsx
> +          tableSorting
done

2022-12-08 17:16 UTC, benjaminchardin2 commented on templates/admin/src/components/theme/list/filter/MultipleChoiceFilterMenu.tsx
> +                        />
done

2022-12-08 17:16 UTC, benjaminchardin2 commented on templates/front/assets/scss/components/_popin.scss
>      overflow: auto;
done

2022-12-08 17:17 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-theme/action/ActionProps.ts
> +  variant?: 'contained' | 'outlined' | 'text'
done

2022-12-08 17:17 UTC, benjaminchardin2 commented on templates/admin/src/i18n/translations/Translations.ts
> +  }
done

2022-12-08 17:17 UTC, benjaminchardin2 commented on templates/admin/src/i18n/translations/Translations.ts
> +  }
done

2022-12-08 17:18 UTC, benjaminchardin2 commented on templates/admin/src/i18n/translations/en.ts
> +      fullName_asc: 'Sort by ascendant alphabetical order',
c'est parce que c'est des lignes de textes donc sans précision tu sais pas si ça tri vers le haut après on pourrait mettre des icones

2022-12-08 17:18 UTC, benjaminchardin2 commented on templates/admin/src/i18n/translations/fr.ts
> +      fullName_asc: 'Trier par ordre alphabétique ascendant',
same

2022-12-08 17:18 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-theme/list/filter/FilterProps.ts
> +  possibleValues: string[]
done

2022-12-08 17:18 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/components/UserTile.tsx
> +            `}
done

2022-12-08 17:18 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/components/UsersListResults.tsx
> +  table: TableType<AdminUserDetails>
done

2022-12-08 17:19 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/pages/Users.tsx
> +    const userLoader = useLoader();
done

2022-12-08 17:19 UTC, benjaminchardin2 commented
Merci beaucoup pour les retours @prateau ! 🤩

2023-03-23 18:32 UTC, amanteaux requested changes

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/components/UserTile.tsx
> +  ) => `${getFirstLetterOfWordCapitalized(fullName, 0)} ${getFirstLetterOfWordCapitalized(fullName, 1)}`;
Il faudrait factoriser ce code avec ce qui est affiché dans le header

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/components/UsersListResults.tsx
> +function UsersListResults(
Ce composant est inutilisé finalement. C'est à jeter ?

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +import UsersListResults from '../components/UsersListResults';
Import inutile

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/components/theme/layout/StatusDot.tsx
> +export default function StatusDot({ status }: StatusDotProps): JSX.Element {
C'est quoi un statusDot ?

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-theme/list/TableProps.ts
> +  usersPath: string
Il faudrait rendre ça générique

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-theme/list/TableProps.ts
> +  rowSelection: { [p: string]: boolean },
Ici comme côté usersList il faudrait revoir le type et surement l'exporter dans un type dédié

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/components/theme/utils/SortUtils.ts
> +export function createCustomCompareSorting<T>(
C'est pour faire quoi ça ?

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/src/components/theme/list/filter/MultipleChoiceFilterMenu.tsx
> +            header.column.getCanFilter() ? (
Donc pour permettre le filtre sur une colonne, dans la définition de la table, il faut préciser `canFilter: true` ? Ou jusetment `canFilter: false` car true est le défaut ?

2023-03-23 18:32 UTC, amanteaux commented on templates/admin/assets/scss/_mixins.scss
> +@mixin dot($size) {
C'est pour quoi ça ?

2023-03-27 13:36 UTC, benjaminchardin2 commented on templates/admin/assets/scss/_mixins.scss
> +@mixin dot($size) {
c'est pour faire un point vert ou rouge selon si le compte de l'utilisateur est actif ou non apparemment

2023-03-27 13:44 UTC, benjaminchardin2 commented on templates/admin/assets/scss/components/_sort-menu.scss
> +  height: 38px;
done

2023-03-27 13:44 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +    const [rowSelection, setRowSelection] = React.useState<{ [p: string]: boolean }>({});
done

2023-03-27 13:44 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +        cell: (info) => info.renderValue(),
done

2023-03-27 13:45 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +      columnHelper.accessor('userName', {
done

2023-03-27 13:45 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +      debugTable: true,
à virer même le debugging est fait 🙈

2023-03-27 14:03 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +      onSortingChange: setSorting,
done

2023-03-27 14:20 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/components/TableResults.tsx
> +function TableResults<T>(
yes c'était le but j'avais mis le header pour des tests j'ai retiré c'est full générique à voir si les actions devraient pas l'être aussi (en attendant j'ai laissé update et delete

2023-03-27 14:21 UTC, benjaminchardin2 commented on templates/admin/src/lib/plume-admin-users/components/TableResults.tsx
> +            </ActionsContainer>
Si mais du coup est-ce que les boutons devraient pas être une liste au final ?

2023-03-29 08:44 UTC, amanteaux requested changes

2023-03-29 08:44 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/pages/Users.tsx
> +            isUsersLoading={isLoading}
A rediscuter

2023-03-31 09:44 UTC, merged