ADD Storybook on Front template
Coreoz/create-plume-react-project pull request #18
Opened 2023-10-13 14:16 UTC by dokor

- ADD storybook 
- ADD storybook dependencies 
- Implement an example

2023-10-18 09:49 UTC, amanteaux requested changes

2023-10-18 13:06 UTC, dokor commented on templates/front/.storybook/preview.ts
> +import '../assets/scss/app.scss';
Yes j'en ai rediscuté avec Wail spécifiquement, ce fichier corresponds bien au style global de l'appli. On veut donc que ce fichier soit importé. Pour le coup, les modules scss des composants seront importés directement par les composants en question. 

La problématique qui justifie vraiment l'import du app.scss : 
On veut qu'un composant qui a son module css ET/OU qui utilise une classe global puisse fonctionner correctement.

2023-10-19 10:44 UTC, amanteaux commented
Est-ce qu'il faut aussi l'ajouter sur le template d'admin ?

2023-10-19 10:46 UTC, amanteaux commented
Et idéalement, je me dis que ça serait bien de faire un petit readme dans le dossier `src/stories` pour expliquer rapidement comment ça marche et référencer la documentation officielle

2023-10-20 10:50 UTC, dokor commented
La partie admin viendra dans un second temps, car pour le coup il y a un peu plus de matière en terme de composants.

Yes je mets à jour le readme.

2023-10-20 16:16 UTC, merged