CSS Modules
Coreoz/create-plume-react-project pull request #22
Opened 2024-01-16 12:24 UTC by vincentdbs

- Change css module convention to camelCase
- Add classNameBuilder
- Add guide in readme if we want to add a mixin folder imported by default

2024-01-17 09:53 UTC, lucas-amiaud requested changes

2024-01-17 09:53 UTC, lucas-amiaud commented on templates/front/src/utils/StyleUtils.ts
> +const classNameBuilder = (classNameByConditions: ClassNameByConditions[], baseClassName?: string): string => {
Je trouve la signature de cette fonction trop confusante, ca peut faire plein de choses en en même temps c'est pas générique. Pourquoi pas avoir un classNameBuilder, mais il faut qu'à l'appel les arguments soient plus parlants. Je vois par exemple plus haut : 
```js
classNameBuilder([[!isDrawerOpened, 'nav--reduced']], 'main-nav nav')
```
mais en vrai, au premier coup d'oeil je sais pas ce que ca fait.
Je verrais plus un truc comme : 
```js
type ClassNames = string | undefined | null | false;

function computeClassName(baseClassName: string | undefined, classes: { [key: string]: boolean } | ClassNames[]) { ... }
```
que tu pourrais appeler comme ca (cet exemple n'a aucun sens, mais c'est pour démontrer): 
```js
const isActive = true;
const isDisabled = false;

const customClasses = ['extra-class-1', 'extra-class-2'];

const dynamicClassNames = buildClassName('base-class', {
  'active-class': isActive,
  'disabled-class': isDisabled,
  ...customClasses.reduce((acc, className) => ({ ...acc, [className]: true }), {}),
}); 
```

2024-01-18 15:20 UTC, amanteaux commented on templates/front/README.md
> +- `src/utils`: Container utility functions
Je ferai bien la suppression de ça :
- Soit on met le code spécifique dans le dossier lib
- Soit justement on passe par une lib

C'est très souvent une mauvaise pratique le code utilitaire qui "traine"

2024-02-22 12:29 UTC, vincentdbs commented
Remplacé par https://github.com/Coreoz/create-plume-react-project/pull/30

2024-02-22 12:29 UTC, closed without merging