review general layout + upgrade libraries
Coreoz/create-plume-react-project pull request #35
Opened 2024-04-18 13:06 UTC by lucas-amiaud

2024-04-22 09:26 UTC, GeoffreyEhrmann approved these changes

2024-04-22 09:41 UTC, GeoffreyEhrmann commented on templates/admin/assets/scss/layouts/_layout.scss
> +.panel {
J'ai l'impression qu'on est plus sur du layout général à partir d'ici 
On pourrait mettre ça dans un fichier dédié _panel.scss

2024-04-22 09:41 UTC, GeoffreyEhrmann commented on templates/admin/src/components/features/Home.tsx
> +    </theme.panel>
c'est personnel, mais j'aime vraiment pas la syntaxe `<theme.panel>`, on peut pas destruct `panel` depuis le thème et l'utiliser directement 

```
const { panel } = theme;

<panel>
```

Voire 
```
const { panel: Panel } = theme;

<Panel>
```
Parce que c'est plus joli

2024-04-29 17:17 UTC, amanteaux requested changes

2024-04-29 17:17 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/pages/UsersEdit.tsx
> +        <this.theme.actionsContainer cssClasses="actions--end">
Est-ce que ça ne devrait pas être une props optionnelle du container ? En lisant la classe je devine que ça pourrait être `verticalPosition`

2024-04-29 17:17 UTC, amanteaux commented on templates/admin/assets/scss/features/_login.scss
> +  .login-icon {
Est-ce que tu voudrais faire un premier pas vers les CSS modules et mettre ça à côté du Login ? Ou justement dans un second temps ?

2024-04-29 17:17 UTC, amanteaux commented on templates/admin/src/components/hooks/ThemeHook.ts
> +function usePlumeTheme(): PlumeAdminThemeComponents {
ça serait pas plus simple de juste mettre des majuscules sur les variables du theme ?

2024-04-29 17:17 UTC, amanteaux commented on templates/admin/src/components/features/Home.tsx
> +  const { Panel, PanelTitle }: PlumeAdminThemeComponents = usePlumeTheme();
Pour les composants génériques comme les pages users je comprends bien l'intérêt de faire ça plutôt que les imports simples, mais pour les pages du projet, j'ai plus de mal à voir. C'est pour permettre de voir les options disponibles ?

2024-04-30 07:46 UTC, lucas-amiaud commented on templates/admin/src/lib/plume-admin-users/pages/UsersEdit.tsx
> +        <this.theme.actionsContainer cssClasses="actions--end">
Yes, j'avais commencé à le faire dans un MR séparée. J'avais nommé la props "position", mais je peux préciser vertical

2024-04-30 07:50 UTC, lucas-amiaud commented on templates/admin/src/components/hooks/ThemeHook.ts
> +function usePlumeTheme(): PlumeAdminThemeComponents {
ha ca serait plus simple ! mais je me suis juste dit que vu que c'est déclaré dans une classe , c'est peut être pas tip top d'avoir des fonctions avec des majuscules mais ca se fait aussi

2024-07-03 11:20 UTC, lucas-amiaud commented on templates/admin/assets/scss/features/_login.scss
> +  .login-icon {
Cf autre PR

2024-07-12 17:17 UTC, merged