Feature/jest
Coreoz/create-plume-react-project pull request #40
Opened 2024-08-20 12:25 UTC by vincentdbs

2024-08-21 14:04 UTC, amanteaux requested changes
Je suis par contre un peu géné par rapport à la PR de Lucas, https://github.com/Coreoz/create-plume-react-project/pull/38, qui va être encore plus compliquée à merger si je fusionne ta PR en premier.

Idéalement j'aimerais bien merger la PR de Lucas à qui je viens de faire des retours avant de merger cette PR.

2024-08-21 15:50 UTC, amanteaux commented on templates/admin/src/components/theme/form/fields/InputText.tsx
> +      //@ts-ignore
On peut pas faire sans le ts ignore au fait ? Avec un any ou autre chose ?

2024-08-21 16:12 UTC, vincentdbs commented on templates/admin/src/components/theme/form/fields/InputText.tsx
> +      //@ts-ignore
Nope parce que InputText ne définit pas la props data-testid mais qui est valide au niveau des éléments du dom. Mais je suis d'accord que c'est un peu moche

2024-08-21 16:12 UTC, vincentdbs commented on templates/admin/src/lib/plume-admin-theme/form/FormInputProps.ts
> +  dataTestId?: string,
J'ai ajouté le commentaire et extrait dans un type

2024-08-22 14:15 UTC, amanteaux commented on templates/admin/src/components/theme/form/fields/InputText.tsx
> +      //@ts-ignore
Je l'ai eu hehe, tu peux remplacer ta ligne du dessous avec `InputProps={dataTestId ? { 'data-testid': dataTestId } as InputProps : undefined}`

2024-08-22 14:17 UTC, amanteaux commented on templates/admin/src/components/theme/form/fields/InputText.tsx
> +      //@ts-ignore
Globalement j'essaie à chaque fois de passer par tous les hacks possibles avant d'utiliser `//@ts-ignore`, car le problème de `//@ts-ignore` c'est qu'il ignore toutes les règles de compilation côté TS pour la ligne d'après : du coup on peut avoir des erreurs de compilation basiques qu'on ne voit pas (c'est déjà arrivé dans la stack avant qu'on tue tous les `//@ts-ignore`)

2024-08-22 15:11 UTC, merged