fix popin layout and user form
Coreoz/create-plume-react-project pull request #41
Opened 2024-08-28 10:02 UTC by lucas-amiaud

2024-09-03 13:20 UTC, amanteaux requested changes

2024-09-03 13:56 UTC, lucas-amiaud commented on templates/admin/assets/scss/_material-override.scss
> +  color: currentColor;
normalement ca fait référence à la couleur en cours .. j'avoue que c'était déjà là, et je suis pas sûr de l'intérêt

2024-09-03 13:56 UTC, lucas-amiaud commented on templates/admin/src/lib/plume-admin-users/pages/UsersEdit.tsx
> +      <ConfirmationPopIn {...popInProps} />
c'est à dire dans un fragment pour que les deux popin soient cote cote ?

2024-09-17 15:05 UTC, amanteaux commented on templates/admin/assets/scss/_material-override.scss
> +  color: currentColor;
Tu peux essayer de le supprimer ? Car c'est bizarre, ce n'est pas une variable... Je ne vois pas comment ça fonctionne et si ça fonctionne

2024-09-17 15:08 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/pages/UsersEdit.tsx
> +      <ConfirmationPopIn {...popInProps} />
Alors je me suis trompé, mais d'un point de vue logique, je l'aurais bien mise avant la déclaration du `FormContainer`

2024-09-18 14:24 UTC, lucas-amiaud commented on templates/admin/src/lib/plume-admin-users/pages/UsersEdit.tsx
> +      <ConfirmationPopIn {...popInProps} />
C'est fait

2024-09-18 14:24 UTC, lucas-amiaud commented on templates/admin/assets/scss/_material-override.scss
> +  color: currentColor;
C'est fait

2024-09-26 15:20 UTC, merged