implem sort handling and ui
Coreoz/create-plume-react-project pull request #43
Opened 2024-09-06 12:15 UTC by lucas-amiaud

![image](https://github.com/user-attachments/assets/c5ea7850-de46-4cb2-837e-a3a932ab346a)

In ths PR : 
- Sort handling (managing in hook + UI)
- UI integration of the sort select (creation of listHead)
- more believable filter for the UI

2024-09-17 16:42 UTC, amanteaux requested changes

2024-09-17 16:42 UTC, amanteaux commented on templates/admin/src/components/theme/list/ListHead.tsx
> +function ListHead({ title, isLoading, children }: PropsWithChildren<ListHeadProps>) {
`SearchResultHeader` ?

2024-09-17 16:42 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +        object: currentSort,
Mêmes retours que sur l'autre PR avec `object` et `apply`

2024-09-17 16:42 UTC, amanteaux commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +              <SortSelect<UserSort>
C'est valide comme JSX ça ?

2024-09-17 16:42 UTC, amanteaux commented on templates/admin/src/lib/plume-search/sorts/SortFunctions.ts
> +function compareAlphanumeric(aStr: string, bStr: string) {
Il faudrait faire des TU sur ça

2024-09-17 16:42 UTC, amanteaux commented on templates/admin/src/lib/plume-search/sorts/SortFunctions.ts
> +function withSortDirection<T>(
Il faudrait commenter la fonction, son usage n'est pas hyper clair

2024-09-17 16:43 UTC, amanteaux commented
@vincentdbs et @Wail-LT Vous avez des remarques sur ça ? Vous pouvez regarder directement le fichier `UsersList.tsx` ou c'est utilisé, sinon c'est long.

2024-09-18 07:08 UTC, vincentdbs commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +              <SortSelect<UserSort>
c'est pour typer le composant générique <SortSelect>

2024-09-18 07:08 UTC, vincentdbs commented on templates/admin/src/lib/plume-search/SearchLazyLoadedDataHook.ts
> +type SearchLazyLoadedDataOptions<F, S> = {
il y a pas des noms plus clairs pour les génériques F, S, T pour que ce soit plus clair à la lecture ?

2024-09-18 07:08 UTC, vincentdbs commented on templates/admin/src/lib/plume-search/SearchLoadedDataHook.ts
> +type SearchLoadedDataHookOptions<T, F, S extends string> = {
pareil

2024-09-18 07:08 UTC, vincentdbs commented on templates/admin/src/lib/plume-admin-users/pages/UsersList.tsx
> +const filterLastLoginDateFromOption = (value: AdminUserDetails, option: CreationDateOption | undefined) => {
```suggestion
const filterLastLoginDateFromOption = (value: AdminUserDetails, option?: CreationDateOption) => {
```

2024-09-20 09:59 UTC, merged