Mise en place des Scss modules
Coreoz/create-plume-react-project pull request #7
Opened 2022-07-17 13:25 UTC by WellsL

2023-04-27 10:01 UTC, amanteaux requested changes

2023-04-27 10:01 UTC, amanteaux commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
Il faudrait mettre `@use '@scssVariables' as *; `partout non ?

2023-04-27 10:01 UTC, amanteaux commented on templates/front/src/components/app.module.scss
> +.app {
Il est utilisé par qui ce fichier SCSS ?

2023-04-27 10:13 UTC, WellsL commented on templates/front/asset.d.ts
> +/// <reference types="vite/client" />
ça permet d'utiliser les types fournis par vite

2023-04-27 10:16 UTC, WellsL commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
Yes pas faux, je crois que j'avais rencontré des problèmes avec ça je vais réessayer !

2023-04-27 10:18 UTC, WellsL commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
Au niveau du build, c'est du js donc pas besoin des types. Les types sont uniquement utilisés pour le dev.

2023-04-27 10:18 UTC, WellsL commented on templates/front/vite.config.ts
> +import react from '@vitejs/plugin-react';
Yep !

2023-04-27 10:46 UTC, amanteaux commented on templates/front/asset.d.ts
> +/// <reference types="vite/client" />
On parle de quels types en fait concrètement ? C'est bizarre comme syntaxe en plus, on dirait des commentaires, c'est vraiment pris en compte ?

2023-04-27 10:46 UTC, amanteaux commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
uh ! Tu pourrais ajouter l'explication dans le fichier `.gitignore` ?

2023-04-28 09:00 UTC, GeoffreyEhrmann commented on templates/front/src/components/pages/Home.tsx
> +  return <div id={scss.homeLayout}>
Juste pour savoir, l'IDE fait bien le lien entre la classe et la variable ? (pour pouvoir faire un ctrl+click et voir les utilisations)

2023-04-28 09:00 UTC, GeoffreyEhrmann commented on templates/front/tsconfig.json
> +      {"transform": "./non-ts-module-import-transformer.ts"}
ctrl + alt +L pour la syntaxe

2023-06-11 13:22 UTC, WellsL commented on templates/front/src/components/pages/Home.tsx
> +  return <div id={scss.homeLayout}>
Yes il fait le lien

2023-06-12 20:54 UTC, Wail-LT commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
J'ai ajouté plusieurs alias, dis moi si j'en fait trop 😅 :

```
      '@scssVariables': require('path').resolve(__dirname, 'assets/scss/variables.scss'),
      '@api': require('path').resolve(__dirname, 'src/api'),
      '@components': require('path').resolve(__dirname, 'src/components'),
      '@i18n': require('path').resolve(__dirname, 'src/i18n'),
      '@lib': require('path').resolve(__dirname, 'src/lib'),
      '@services': require('path').resolve(__dirname, 'src/services'),
```

PI. il y a un plugin vite permettant de récupérer les variables scss dans le JS, Ça pourrait être intéressant de l'intégrer dans la stack, à voir si on en a le besoin !

2023-06-12 20:54 UTC, Wail-LT commented on templates/front/src/components/app.module.scss
> +.app {
yep supprimé

2023-06-12 20:54 UTC, Wail-LT commented on templates/front/tsconfig.json
> +      {"transform": "./non-ts-module-import-transformer.ts"}
yep

2023-06-15 10:25 UTC, amanteaux commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
Je me pose quand même la question, côté CI, ça ne vaudrait pas le coup de faire cette vérification des types ? On pourrait faire ça comment ?

2023-06-15 10:37 UTC, amanteaux requested changes

2023-06-15 10:37 UTC, amanteaux commented on templates/front/typed-scss-modules.config.ts
> +export default {
Il faudrait mettre un commnentaire pour dire : `This is configuration for the ``typed-scss-modules`` package to enable SCSS modules`

2023-06-15 10:37 UTC, amanteaux commented on templates/front/.gitignore
> +# scss types
Ce commentaire n'est plus utile

2023-06-15 10:37 UTC, amanteaux commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
Les alias me semblent bien !

Tu as un cas d'usage pour le plugin vite ?

Tu as toujours des problèmes pour utiliser `@use '@scssVariables' as *;` ?

2023-06-15 10:41 UTC, amanteaux commented
Il faudrait également ajouter une section dans le fichier `README.md` pour :
- Présenter rapidement les modules SCSS et comment les utiliser (en pointant vers les bonnes docs)
- Détailler comment c'est intégré sur notre stack, pour notamment le dev où il y a pas mal de choses qui semblent tourner pour permettre le typage (typed-scss-modules, copy css, vite, ...)
- Les alias : `@scssVariables @api @components @i18n @lib @services`

2023-06-15 11:21 UTC, Wail-LT commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
Top je garde les alias !

Cas d'usage plugin vite : Récupérer les breakpoints css (Mobile, Desktop, Tablet) pour les réutiliser en JS et conditionner l'affichage de composants dédiés à un type de device ou résolution.

Je ne me rappel pas avoir eu de problème avec le `@use '@scssVariables' as *;`
Je voulais l'importer par défaut dans les modules scss, mais finalement je me demande si c'est vraiment nécessaire...

2023-06-15 11:21 UTC, Wail-LT commented on templates/front/assets/scss/_root.scss
> +  flex-direction: column;;
Oupsy

2023-06-15 11:46 UTC, amanteaux commented on templates/front/src/components/pages/Home.tsx
> +
Peut être en effet !

2023-06-15 11:47 UTC, amanteaux commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
Pour le plugin vite pourquoi pas si c'est facile à intégrer.

Après ça semble pas mal sur le papier d'avoir l'import des variables par défaut. Ca éviterait d'avoir à mettre la ligne `@use '@scssVariables' as *;` partout ?

2023-06-15 11:52 UTC, amanteaux commented on templates/front/vite.config.ts
> +        run: 'yarn copy-css',
Humm mais il y a un doublon alors, car tu as la tâche `"watch-scss-module": "concurrently \"typed-scss-modules 'src/**/*.scss' -w\" \"yarn copy-css\"",` qui va elle aussi copier les modules scss dans le dossier `ts-built` à chaque modification non ?

2023-06-24 07:35 UTC, Wail-LT commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
yes en effet, sur automate ça nous avais posé problème car la migration vers les modules scss n'était pas total

2023-06-24 08:24 UTC, Wail-LT commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
c'est fait

2023-06-24 08:29 UTC, Wail-LT commented on templates/front/vite.config.ts
> +        run: 'yarn copy-css',
nop, sorry ce n'est pas claire ce que j'ai fait, j'aurais du faire 2 commandes dans le package.json.

le `yarn copy-css`n'est pas watch

2023-06-24 08:31 UTC, Wail-LT commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
yes c'est possible, je fais ça !

Je serais tout de même curieux de connaître les cas d'usage.

2023-06-24 08:58 UTC, Wail-LT commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
La commande suivante permet de vérifier que les types et les modules scss sont synchro :

<img width="753" alt="image" src="https://github.com/Coreoz/create-plume-react-project/assets/26419988/a6fee043-264f-4ed9-a078-32e79b77164d">

2023-06-24 08:59 UTC, Wail-LT commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
J'ai ajouter une commande dans le package.json : 'check-scss-types'

2023-06-24 09:04 UTC, Wail-LT commented on templates/front/assets/scss/_root.scss
> +  flex-direction: column;;
done

2023-06-24 09:05 UTC, Wail-LT commented on templates/front/src/components/pages/Home.tsx
> +
c'est fait

2023-07-01 14:17 UTC, Wail-LT commented on templates/front/.eslintrc.js
> +    'plugin:css-modules/recommended',
@amanteaux Plugin permettant de créer des erreurs ESLint dès lors que des  classes CSS sont inutilisées :

<img width="839" alt="image" src="https://github.com/Coreoz/create-plume-react-project/assets/26419988/231bc61a-2a1a-471a-9ef8-ad13ba777cba">

2023-07-06 14:02 UTC, amanteaux requested changes

2023-07-06 14:02 UTC, amanteaux commented on templates/front/vite.config.ts
> +        run: 'yarn copy-css',
Et du coup c'est nécessaire d'avoir copy-css dans la tâche start dans le fichier package.json ?

2023-07-06 14:52 UTC, amanteaux commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
On perd l'auto complétion du coup ? Ou celle-ci n'a fonctionné pour les variables SCSS ?

2023-07-06 14:52 UTC, amanteaux commented on templates/front/package.json
> +    "watch-scss-module": "typed-scss-modules 'src/**/*.scss' -w"
Parfait !

2023-07-06 14:57 UTC, Wail-LT commented on templates/front/src/components/layout/header/header.module.scss
> +@use './assets/scss/_variables.scss' as *;
Nop on ne la perd pas

2023-07-06 15:02 UTC, Wail-LT commented on templates/front/vite.config.ts
> +        run: 'yarn copy-css',
si tu modifies ton CSS sans avoir lancé ton projet, il est préférable que le CSS soit copié au démarrage non ?

2023-07-06 15:03 UTC, Wail-LT commented on templates/front/src/components/layout/Layout.tsx
> +import Header from '@components/layout/header/Header';
Yes automatique !

2023-07-06 15:10 UTC, Wail-LT commented on templates/front/assets/scss/_root.scss
> +.app {
Proposition refacto `_variables.scss`: 

![image](https://github.com/Coreoz/create-plume-react-project/assets/26419988/4044889b-4251-4f9c-888a-3b809570119a)

2023-07-06 15:32 UTC, Wail-LT commented on templates/front/assets/scss/_root.scss
> +.app {
Comme vu ensemble, la proposition a été appliquée !

2023-07-10 08:13 UTC, amanteaux commented on templates/front/vite.config.ts
> +        run: 'yarn copy-css',
Oui je comprends !

2023-10-11 13:54 UTC, merged